<a href="https://colab.research.google.com/github/panditamey1/NLP_transformers/blob/main/transformers_pytorch_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Self attention


Key, Query, Value 
- Create matrices for KQV
 

In [108]:
import numpy as np
np.random.seed(42)
from torch import nn
import torch
torch.random.manual_seed(42)

In [ ]:
t = 4
d = 12 # model dimensions

Wk = np.random.randn(d,d)
Wq = np.random.randn(d,d)
Wv = np.random.randn(d,d)

Wk.shape

(12, 12)

In [ ]:
X = np.random.randn(t,d)  # t = token size

In [ ]:
X.shape


(4, 12)

- take dot product of (Q*K.T/np.sqrt(d) )* V

In [ ]:
Q = np.dot(X, Wq)
K = np.dot(X, Wk)

K.shape

(4, 12)

In [ ]:
## dot product of q and k

QK = np.dot(Q,K.T)


In [ ]:
QK = QK / np.sqrt(d)

In [ ]:
## Softmax
def softmax(x):
    e_x = np.exp(x - np.max(x))
    print(e_x.shape)
    res =  e_x / e_x.sum(axis=0) # only difference
    print(res.shape)
    return res
    

In [ ]:
scaled_QK = softmax(QK)
QK.shape

(4, 4)

In [ ]:
V = np.dot(X, Wv)

In [ ]:
V.shape

(4, 12)

In [ ]:
QKV = np.dot(scaled_QK, V)

In [ ]:
QKV.shape

(4, 12)

## Create function for self attention

In [ ]:
def scaled_self_attention(query, key, value):
  key_dim = key.shape[1]
  QK = np.dot(query,key.T)
  #/np.sqrt(key_dim)
  print("---")
  print(QK.shape)
  #sf = nn.Softmax( dim=1)
  scaled_QK = softmax(QK)
  print(scaled_QK.shape)
  QKV = np.dot(scaled_QK, value)
  print(QKV.shape)
  return QKV, scaled_QK

In [ ]:
scaled_self_attention(Q, K, V)

(array([[ 6.59297357e-47,  6.11623018e-47,  2.09227010e-46,
          1.90797248e-46, -1.28153513e-47, -1.09696246e-46,
          2.74316935e-47, -6.58638251e-47, -1.39020227e-46,
          2.01060110e-46,  7.13266126e-47, -1.89522458e-46],
        [ 5.41346164e-40,  4.36153826e-40,  1.57390668e-39,
          1.45347501e-39, -7.28558597e-41, -8.25978126e-40,
          1.33804646e-40, -5.33975408e-40, -1.09072760e-39,
          1.56123496e-39,  5.51334414e-40, -1.46958532e-39],
        [-8.43764302e+00,  8.77144346e+00, -9.46910444e-01,
          2.97250628e+00,  2.36695398e+00, -3.98113213e+00,
         -2.28811882e+00,  4.45762186e+00,  4.50286565e+00,
          1.52476604e+00,  2.72580162e+00, -3.35865925e-01],
        [ 7.66125828e-32, -3.30838028e-32,  8.32463766e-32,
          1.97255430e-32, -6.90215186e-32, -3.29037147e-31,
         -6.06296034e-32,  1.18175743e-31,  1.12543985e-31,
          4.17384358e-32,  1.40384174e-31, -3.48219463e-32]]),
 array([[9.02178750e-65, 3.9612105

## Multi head attention

In [ ]:
seq_len = 3
embed_dim = 4

queries = np.random.rand(seq_len, embed_dim)
keys = np.random.rand(seq_len, embed_dim)
values = np.random.rand(seq_len, embed_dim)

print("Queries:\n", queries)

Queries:
 [[0.28484049 0.03688695 0.60956433 0.50267902]
 [0.05147875 0.27864646 0.90826589 0.23956189]
 [0.14489487 0.48945276 0.98565045 0.24205527]]


In [ ]:
output, attn_weights = scaled_self_attention(queries, keys, values)

print("Output\n", output, "\n")
print("Weights\n", attn_weights)

(3, 3)
(3, 3)
Output
 [[0.34046052 0.3583313  0.65012393 0.09111357]
 [0.40349096 0.37504672 0.71582375 0.1059299 ]
 [0.49985446 0.47074605 0.89351946 0.13143174]] 

Weights
 [[0.3254204  0.28426828 0.26285964]
 [0.29641855 0.31901007 0.33004653]
 [0.37816105 0.39672165 0.40709382]]


In [109]:
batch_size = 1
seq_len = 3
embed_dim = 12
num_heads = 3
head_dim = embed_dim // num_heads

In [29]:
x = np.random.rand(batch_size, seq_len, embed_dim).round(1)
print("Input shape: ", x.shape, "\n")
print("Input:\n", x)

Input shape:  (1, 3, 12) 

Input:
 [[[0.4 1.  0.7 0.6 0.2 0.2 0.1 0.9 0.6 0.7 0.  1. ]
  [0.8 0.2 0.2 0.2 0.3 0.5 0.4 0.3 0.6 0.1 0.3 0.4]
  [0.5 0.8 0.2 0.5 0.6 0.  0.6 0.2 0.1 0.9 1.  0.8]]]


In [ ]:
# The query weights for each head.
wq0 = np.random.rand(embed_dim, head_dim).round(1)
wq1 = np.random.rand(embed_dim, head_dim).round(1)
wq2 = np.random.rand(embed_dim, head_dim).round(1)

# The key weights for each head. 
wk0 = np.random.rand(embed_dim, head_dim).round(1)
wk1 = np.random.rand(embed_dim, head_dim).round(1)
wk2 = np.random.rand(embed_dim, head_dim).round(1)

# The value weights for each head.
wv0 = np.random.rand(embed_dim, head_dim).round(1)
wv1 = np.random.rand(embed_dim, head_dim).round(1)
wv2 = np.random.rand(embed_dim, head_dim).round(1)

In [ ]:
print("The three sets of query weights (one for each head):")
print("wq0:\n", wq0)
print("wq1:\n", wq1)
print("wq2:\n", wq1)

The three sets of query weights (one for each head):
wq0:
 [[0.9 0.6 0.3 0.3]
 [0.7 0.9 0.9 0.8]
 [0.6 0.1 0.2 0.9]
 [0.6 0.  0.1 0.7]]
wq1:
 [[0.  0.2 0.5 0.7]
 [0.7 0.2 0.7 0.2]
 [0.3 0.7 0.6 0.8]
 [0.7 0.6 0.1 0.4]]
wq2:
 [[0.  0.2 0.5 0.7]
 [0.7 0.2 0.7 0.2]
 [0.3 0.7 0.6 0.8]
 [0.7 0.6 0.1 0.4]]


In [ ]:
# Geneated queries, keys, and values for the first head.
q0 = np.dot(x, wq0)
k0 = np.dot(x, wk0)
v0 = np.dot(x, wv0)

# Geneated queries, keys, and values for the second head.
q1 = np.dot(x, wq1)
k1 = np.dot(x, wk1)
v1 = np.dot(x, wv1)

# Geneated queries, keys, and values for the third head.
q2 = np.dot(x, wq2)
k2 = np.dot(x, wk2)
v2 = np.dot(x, wv2)

In [ ]:
print("Q, K, and V for first head:\n")

print(f"q0 {q0.shape}:\n", q0, "\n")
print(f"k0 {k0.shape}:\n", k0, "\n")
print(f"v0 {v0.shape}:\n", v0)

Q, K, and V for first head:

q0 (1, 3, 4):
 [[[1.42 0.36 0.45 1.61]
  [1.6  0.89 0.94 1.79]
  [1.19 0.49 0.44 1.03]]] 

k0 (1, 3, 4):
 [[[1.98 1.47 0.76 1.12]
  [1.61 1.83 0.91 1.5 ]
  [1.36 1.04 0.74 0.98]]] 

v0 (1, 3, 4):
 [[[0.98 0.85 1.   0.68]
  [1.35 0.92 0.85 0.79]
  [0.48 0.85 0.53 0.65]]]


In [ ]:
import tensorflow as tf
def scaled_dot_product_attention(query, key, value, mask=None):
  key_dim = tf.cast(tf.shape(key)[-1], tf.float32)
  scaled_scores = tf.matmul(query, key, transpose_b=True) / np.sqrt(key_dim)

  if mask is not None:
    scaled_scores = tf.where(mask==0, -np.inf, scaled_scores)

  softmax = tf.keras.layers.Softmax()
  weights = softmax(scaled_scores) 
  return tf.matmul(weights, value), weights

In [ ]:
out0, attn_weights0 = scaled_self_attention(q0, k0, v0)

print("Output from first attention head: ", out0, "\n")
print("Attention weights from first head: ", attn_weights0)

ValueError: ignored

In [110]:
batch_size = 1
seq_len = 3
embed_dim = 12
num_heads = 3
head_dim = embed_dim // num_heads

In [111]:
## to overcome problems with numpy dot product for batch
## create torch array

x = torch.randn(batch_size, seq_len, embed_dim)

print("Input shape: ", x.shape, "\n")
print("Input:\n", x)

Input shape:  torch.Size([1, 3, 12]) 

Input:
 tensor([[[ 1.9269,  1.4873,  0.9007, -2.1055,  0.6784, -1.2345, -0.0431,
          -1.6047, -0.7521,  1.6487, -0.3925, -1.4036],
         [-0.7279, -0.5594, -0.7688,  0.7624,  1.6423, -0.1596, -0.4974,
           0.4396,  0.3189, -0.4245,  0.3057, -0.7746],
         [ 0.0349,  0.3211,  1.5736, -0.8455, -1.2742,  2.1228, -1.2347,
          -0.4879, -1.4181,  0.8963,  0.0499,  2.2667]]])


In [112]:
wq0 = torch.rand(embed_dim, head_dim)
wq1 = torch.rand(embed_dim, head_dim)
wq2 = torch.rand(embed_dim, head_dim)

# The key weights for each head. 
wk0 = torch.rand(embed_dim, head_dim)
wk1 = torch.rand(embed_dim, head_dim)
wk2 = torch.rand(embed_dim, head_dim)

# The value weights for each head.
wv0 = torch.rand(embed_dim, head_dim)
wv1 = torch.rand(embed_dim, head_dim)
wv2 = torch.rand(embed_dim, head_dim)

In [113]:
wq0.shape

torch.Size([12, 4])

In [114]:
torch.matmul(x,wq0)

tensor([[[-3.0163e+00,  1.5319e+00,  5.1243e-01,  1.6608e+00],
         [-5.1072e-01, -8.7488e-01,  5.7035e-01, -3.2563e-03],
         [ 3.2986e+00, -7.5188e-02, -1.6818e+00, -1.2551e+00]]])

In [115]:
torch.einsum('bij,jk->bik', x, wq0)

tensor([[[-3.0163e+00,  1.5319e+00,  5.1243e-01,  1.6608e+00],
         [-5.1072e-01, -8.7488e-01,  5.7035e-01, -3.2562e-03],
         [ 3.2986e+00, -7.5188e-02, -1.6818e+00, -1.2551e+00]]])

In [151]:
softmax_function = nn.Softmax(dim=-1)
input = torch.randn(1,3, 3,4)
print(input)
output = softmax_function(input)
output

tensor([[[[ 1.8595,  2.6221,  0.3691,  0.3803],
          [ 0.1990, -0.2361,  0.3034, -0.4501],
          [ 0.4739,  0.6503,  1.1662,  0.0169]],

         [[ 0.5326, -0.6035, -0.1743,  0.6092],
          [-0.8032, -1.1209,  0.1956, -0.7815],
          [-0.9086,  0.3130,  0.8050, -1.1134]],

         [[ 0.5258,  1.6828,  0.0967,  0.2571],
          [ 0.6378,  0.1598,  1.7698,  0.6268],
          [-0.4976, -0.1823, -0.2120,  0.8162]]]])


tensor([[[[0.2780, 0.5960, 0.0626, 0.0633],
          [0.3049, 0.1973, 0.3385, 0.1593],
          [0.2073, 0.2473, 0.4142, 0.1312]],

         [[0.3456, 0.1109, 0.1704, 0.3731],
          [0.1830, 0.1332, 0.4968, 0.1870],
          [0.0930, 0.3154, 0.5159, 0.0758]],

         [[0.1787, 0.5683, 0.1164, 0.1366],
          [0.1751, 0.1086, 0.5431, 0.1732],
          [0.1347, 0.1847, 0.1793, 0.5013]]]])

In [152]:
def scaled_self_attention_torch(query, key, value):
  key_dim = key.shape[-1]
  QK = torch.div(torch.matmul(query,key.T),np.sqrt(key_dim))
  print("---")
  print(QK.shape)
  #sf = nn.Softmax( dim=1)
  scaled_QK = softmax_function(QK)
  print(scaled_QK.shape)
  QKV = torch.matmul(scaled_QK, value)
  print(QKV.shape)
  return QKV, scaled_QK

In [153]:
# Geneated queries, keys, and values for the first head.
q0 = torch.matmul(x, wq0)
k0 = torch.matmul(x, wk0)
v0 = torch.matmul(x, wv0)

# Geneated queries, keys, and values for the second head.
q1 = torch.matmul(x, wq1)
k1 = torch.matmul(x, wk1)
v1 = torch.matmul(x, wv1)

# Geneated queries, keys, and values for the third head.
q2 = torch.matmul(x, wq2)
k2 = torch.matmul(x, wk2)
v2 = torch.matmul(x, wv2)

In [154]:
print("Q, K, and V for first head:\n")

print(f"q0 {q0.shape}:\n", q0, "\n")
print(f"k0 {k0.shape}:\n", k0, "\n")
print(f"v0 {v0.shape}:\n", v0)

Q, K, and V for first head:

q0 torch.Size([1, 3, 4]):
 tensor([[[-3.0163e+00,  1.5319e+00,  5.1243e-01,  1.6608e+00],
         [-5.1072e-01, -8.7488e-01,  5.7035e-01, -3.2563e-03],
         [ 3.2986e+00, -7.5188e-02, -1.6818e+00, -1.2551e+00]]]) 

k0 torch.Size([1, 3, 4]):
 tensor([[[ 0.0080, -0.4441, -0.3962,  0.0140],
         [-1.2463, -0.5058, -0.2431,  1.1875],
         [ 3.4878,  0.3210,  1.5877, -1.9066]]]) 

v0 torch.Size([1, 3, 4]):
 tensor([[[-0.8313, -1.2514,  2.0560, -2.1358],
         [ 0.7614, -0.5448, -0.9581,  1.5510],
         [-0.2805,  1.5310,  0.7963,  0.5893]]])


In [40]:
out0, attn_weights0 = scaled_self_attention_torch(q0, k0, v0)

print("Output from first attention head: ", out0, "\n")
print("Attention weights from first head: ", attn_weights0)

<ipython-input-37-331783bca393>:3: UserWarning: The use of `x.T` on tensors of dimension other than 2 to reverse their shape is deprecated and it will throw an error in a future release. Consider `x.mT` to transpose batches of matrices or `x.permute(*torch.arange(x.ndim - 1, -1, -1))` to reverse the dimensions of a tensor. (Triggered internally at ../aten/src/ATen/native/TensorShape.cpp:3277.)
  QK = torch.div(torch.matmul(query,key.T),np.sqrt(key_dim))


RuntimeError: ignored

In [94]:
q0

tensor([[[ 0.6788,  1.7449, -0.4234,  0.7830],
         [-0.5399,  0.5887, -0.0268, -1.2599],
         [ 2.4524,  2.3112,  1.5315,  0.1854]]])

In [95]:
k0

tensor([[[ 1.4471,  0.4132,  1.3002,  1.5290],
         [-0.7078,  1.5979, -1.0892, -0.1337],
         [-1.7239,  0.2325,  0.2377,  0.6269]]])

In [44]:
k0.T

tensor([[[ 1.4471],
         [-0.7078],
         [-1.7239]],

        [[ 0.4132],
         [ 1.5979],
         [ 0.2325]],

        [[ 1.3002],
         [-1.0892],
         [ 0.2377]],

        [[ 1.5290],
         [-0.1337],
         [ 0.6269]]])

In [96]:
torch.einsum('bij,bkj->bik', q0, k0)

tensor([[[ 2.3498,  2.6644, -0.3742],
         [-2.4992,  1.5205,  0.2715],
         [ 6.7784,  0.2647, -3.2098]]])

In [155]:
## Changing our self attention function

def scaled_self_attention_torch(query, key, value):
  key_dim = key.shape[-1]
  QK = torch.div(torch.einsum('bij,bkj->bik',query,key),np.sqrt(key_dim))
  print("---")
  print(QK.shape)
  #sf = nn.Softmax( dim=1)
  scaled_QK = softmax_function(QK)
  print(scaled_QK.shape)
  QKV = torch.matmul(scaled_QK, value)
  print(QKV.shape)
  return QKV, scaled_QK

In [156]:
out0, attn_weights0 = scaled_self_attention_torch(q0, k0, v0)

print("Output from first attention head: \n", out0, "\n")
print("Attention weights from first head: \n", attn_weights0)

---
torch.Size([1, 3, 3])
torch.Size([1, 3, 3])
torch.Size([1, 3, 4])
Output from first attention head: 
 tensor([[[ 0.6748, -0.5827, -0.7942,  1.3508],
         [ 0.0488, -0.4205,  0.3526,  0.1533],
         [-0.2831,  1.5158,  0.8024,  0.5754]]]) 

Attention weights from first head: 
 tensor([[[5.4253e-02, 9.4557e-01, 1.7291e-04],
         [3.3386e-01, 4.9262e-01, 1.7352e-01],
         [5.2320e-03, 2.7894e-04, 9.9449e-01]]])


In [157]:
out1, _ = scaled_self_attention_torch(q1, k1, v1)
out2, _ = scaled_self_attention_torch(q1, k1, v1)


---
torch.Size([1, 3, 3])
torch.Size([1, 3, 3])
torch.Size([1, 3, 4])
---
torch.Size([1, 3, 3])
torch.Size([1, 3, 3])
torch.Size([1, 3, 4])


In [158]:
combined_out_a = torch.concatenate([out0,out1, out2], axis  = -1)

In [159]:
print(f"Combined output from all heads {combined_out_a.size()} :")

Combined output from all heads torch.Size([1, 3, 12]) :


In [160]:
combined_out_a

tensor([[[ 0.6748, -0.5827, -0.7942,  1.3508,  2.1227, -1.9256,  0.6278,
          -2.3120,  2.1227, -1.9256,  0.6278, -2.3120],
         [ 0.0488, -0.4205,  0.3526,  0.1533,  0.7703, -0.3158,  0.4023,
          -0.9044,  0.7703, -0.3158,  0.4023, -0.9044],
         [-0.2831,  1.5158,  0.8024,  0.5754, -0.9044, -0.6448, -0.8448,
           0.0312, -0.9044, -0.6448, -0.8448,  0.0312]]])

## just single weight matrix

In [161]:
wq = torch.concatenate([wq0,wq1,wq2], axis = -1)

In [162]:
wk = torch.concatenate([wk0,wk1,wk2], axis = -1)
wv = torch.concatenate([wv0,wv1,wv2], axis = -1)

In [163]:
wq.size()

torch.Size([12, 12])

In [164]:
q_s = torch.matmul(x, wq)
k_s = torch.matmul(x, wk)
v_s = torch.matmul(x, wv)


In [165]:
q_s.size()

torch.Size([1, 3, 12])

In [166]:
q_s

tensor([[[-3.0163e+00,  1.5319e+00,  5.1243e-01,  1.6608e+00, -2.6275e+00,
          -9.8147e-01, -1.0185e+00, -1.5966e+00,  1.7143e-01, -2.2158e+00,
           3.7624e-01,  5.6532e-01],
         [-5.1072e-01, -8.7488e-01,  5.7035e-01, -3.2563e-03,  1.0849e+00,
          -7.0866e-01, -8.3605e-01, -6.1532e-01, -7.1942e-01, -5.7810e-02,
          -7.0680e-01,  6.2113e-01],
         [ 3.2986e+00, -7.5188e-02, -1.6818e+00, -1.2551e+00,  3.4234e-01,
           6.4476e-01,  3.0574e+00,  2.3347e+00,  1.6309e+00,  1.4771e+00,
           1.1949e+00,  5.8007e-01]]])

In [167]:
q_s_reshaped = torch.reshape(q_s, [batch_size, seq_len, num_heads, head_dim])
q_s_reshaped.size()

torch.Size([1, 3, 3, 4])

In [168]:
q_s_reshaped

tensor([[[[-3.0163e+00,  1.5319e+00,  5.1243e-01,  1.6608e+00],
          [-2.6275e+00, -9.8147e-01, -1.0185e+00, -1.5966e+00],
          [ 1.7143e-01, -2.2158e+00,  3.7624e-01,  5.6532e-01]],

         [[-5.1072e-01, -8.7488e-01,  5.7035e-01, -3.2563e-03],
          [ 1.0849e+00, -7.0866e-01, -8.3605e-01, -6.1532e-01],
          [-7.1942e-01, -5.7810e-02, -7.0680e-01,  6.2113e-01]],

         [[ 3.2986e+00, -7.5188e-02, -1.6818e+00, -1.2551e+00],
          [ 3.4234e-01,  6.4476e-01,  3.0574e+00,  2.3347e+00],
          [ 1.6309e+00,  1.4771e+00,  1.1949e+00,  5.8007e-01]]]])

In [169]:
q_s_transposed = torch.transpose(q_s_reshaped,1,2)
q_s_transposed

tensor([[[[-3.0163e+00,  1.5319e+00,  5.1243e-01,  1.6608e+00],
          [-5.1072e-01, -8.7488e-01,  5.7035e-01, -3.2563e-03],
          [ 3.2986e+00, -7.5188e-02, -1.6818e+00, -1.2551e+00]],

         [[-2.6275e+00, -9.8147e-01, -1.0185e+00, -1.5966e+00],
          [ 1.0849e+00, -7.0866e-01, -8.3605e-01, -6.1532e-01],
          [ 3.4234e-01,  6.4476e-01,  3.0574e+00,  2.3347e+00]],

         [[ 1.7143e-01, -2.2158e+00,  3.7624e-01,  5.6532e-01],
          [-7.1942e-01, -5.7810e-02, -7.0680e-01,  6.2113e-01],
          [ 1.6309e+00,  1.4771e+00,  1.1949e+00,  5.8007e-01]]]])

In [170]:
k_s_transposed =torch.transpose(torch.reshape(k_s, [batch_size, seq_len, num_heads, head_dim]),1,2)
v_s_transposed =torch.transpose(torch.reshape(v_s, [batch_size, seq_len, num_heads, head_dim]),1,2)


In [171]:
q_s_transposed.size()

torch.Size([1, 3, 3, 4])

In [65]:
## make a single call to self attention

out, attn_weights = scaled_self_attention_torch(q_s_transposed, k_s_transposed, v_s_transposed)


RuntimeError: ignored

In [107]:
## make the necessary changes to the function
print(q_s_transposed.size(), " - ",  torch.transpose(k_s_transposed,-1,-2).size())
torch.matmul(q_s_transposed, torch.transpose(k_s_transposed,-1,-2))

torch.Size([1, 3, 3, 4])  -  torch.Size([1, 3, 4, 3])


tensor([[[[ 2.3498,  2.6644, -0.3742],
          [-2.4992,  1.5205,  0.2715],
          [ 6.7784,  0.2647, -3.2098]],

         [[ 9.2551,  1.0072,  2.7328],
          [ 4.6929, -0.0826,  2.2253],
          [ 9.0149,  3.6956,  4.9875]],

         [[11.9529,  3.0278, 13.9837],
          [-0.2167, -0.2847,  0.3090],
          [ 7.2083,  1.6485,  8.4704]]]])

In [77]:
torch.einsum('bsij,bskj->bsik',q_s_transposed,k_s_transposed)

tensor([[[[ 2.3498,  2.6644, -0.3742],
          [-2.4992,  1.5205,  0.2715],
          [ 6.7784,  0.2647, -3.2098]],

         [[ 9.2551,  1.0072,  2.7328],
          [ 4.6929, -0.0826,  2.2253],
          [ 9.0149,  3.6956,  4.9875]],

         [[11.9529,  3.0278, 13.9837],
          [-0.2167, -0.2847,  0.3090],
          [ 7.2083,  1.6485,  8.4704]]]])

In [78]:
k_s_transposed.size()

torch.Size([1, 3, 3, 4])

In [172]:
## Changing our self attention function

def scaled_self_attention_torch(query, key, value):
  key_dim = key.shape[-1]
  key_reshape = torch.transpose(key,-1,-2)
  #QK = torch.div(torch.einsum('bsij,bskj->bsik',query,key),np.sqrt(key_dim))
  QK = torch.div(torch.matmul(query,key_reshape),np.sqrt(key_dim))
  print("---")
  print(QK.shape)
  #sf = nn.Softmax( dim=1)
  scaled_QK = softmax_function(QK)
  print(scaled_QK.shape)
  QKV = torch.matmul(scaled_QK, value)
  print(QKV.shape)
  return QKV, scaled_QK

In [173]:
out, attn_weights = scaled_self_attention_torch(q_s_transposed, k_s_transposed, v_s_transposed)
out.size()

---
torch.Size([1, 3, 3, 3])
torch.Size([1, 3, 3, 3])
torch.Size([1, 3, 3, 4])


torch.Size([1, 3, 3, 4])

In [174]:
out

tensor([[[[ 0.6748, -0.5827, -0.7942,  1.3508],
          [ 0.0488, -0.4205,  0.3526,  0.1533],
          [-0.2831,  1.5158,  0.8024,  0.5754]],

         [[ 2.1227, -1.9256,  0.6278, -2.3120],
          [ 0.7703, -0.3158,  0.4023, -0.9044],
          [-0.9044, -0.6448, -0.8448,  0.0312]],

         [[-1.6386,  0.4759, -0.4717,  2.2239],
          [-0.4508,  0.1738, -0.2344,  0.8132],
          [ 1.4882,  0.6556, -0.9764,  1.6874]]]])

In [175]:
attn_weights

tensor([[[[5.4253e-02, 9.4557e-01, 1.7291e-04],
          [3.3386e-01, 4.9262e-01, 1.7352e-01],
          [5.2320e-03, 2.7894e-04, 9.9449e-01]],

         [[9.9958e-01, 3.8871e-04, 3.6176e-05],
          [4.9419e-01, 1.6953e-01, 3.3627e-01],
          [1.5876e-04, 8.6969e-01, 1.3015e-01]],

         [[8.6893e-01, 9.9629e-02, 3.1445e-02],
          [2.7580e-01, 4.5759e-01, 2.6661e-01],
          [9.2030e-03, 9.4160e-02, 8.9664e-01]]]])

In [176]:
out0

tensor([[[ 0.6748, -0.5827, -0.7942,  1.3508],
         [ 0.0488, -0.4205,  0.3526,  0.1533],
         [-0.2831,  1.5158,  0.8024,  0.5754]]])

In [177]:
combined_out_b = torch.reshape(torch.transpose(out,1,2), shape=[batch_size, seq_len, embed_dim])

In [178]:
combined_out_b

tensor([[[ 0.6748, -0.5827, -0.7942,  1.3508,  2.1227, -1.9256,  0.6278,
          -2.3120, -1.6386,  0.4759, -0.4717,  2.2239],
         [ 0.0488, -0.4205,  0.3526,  0.1533,  0.7703, -0.3158,  0.4023,
          -0.9044, -0.4508,  0.1738, -0.2344,  0.8132],
         [-0.2831,  1.5158,  0.8024,  0.5754, -0.9044, -0.6448, -0.8448,
           0.0312,  1.4882,  0.6556, -0.9764,  1.6874]]])

In [179]:
combined_out_a

tensor([[[ 0.6748, -0.5827, -0.7942,  1.3508,  2.1227, -1.9256,  0.6278,
          -2.3120,  2.1227, -1.9256,  0.6278, -2.3120],
         [ 0.0488, -0.4205,  0.3526,  0.1533,  0.7703, -0.3158,  0.4023,
          -0.9044,  0.7703, -0.3158,  0.4023, -0.9044],
         [-0.2831,  1.5158,  0.8024,  0.5754, -0.9044, -0.6448, -0.8448,
           0.0312, -0.9044, -0.6448, -0.8448,  0.0312]]])