<a href="https://colab.research.google.com/github/panditamey1/NLP_transformers/blob/main/transformers_pytorch_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Self attention


Key, Query, Value 
- Create matrices for KQV
 

In [4]:
import numpy as np
np.random.seed(42)
from torch import nn
import torch

In [ ]:
t = 4
d = 12 # model dimensions

Wk = np.random.randn(d,d)
Wq = np.random.randn(d,d)
Wv = np.random.randn(d,d)

Wk.shape

(12, 12)

In [ ]:
X = np.random.randn(t,d)  # t = token size

In [ ]:
X.shape


(4, 12)

- take dot product of (Q*K.T/np.sqrt(d) )* V

In [ ]:
Q = np.dot(X, Wq)
K = np.dot(X, Wk)

K.shape

(4, 12)

In [ ]:
## dot product of q and k

QK = np.dot(Q,K.T)


In [ ]:
QK = QK / np.sqrt(d)

In [ ]:
## Softmax
def softmax(x):
    e_x = np.exp(x - np.max(x))
    print(e_x.shape)
    res =  e_x / e_x.sum(axis=0) # only difference
    print(res.shape)
    return res
    

In [ ]:
scaled_QK = softmax(QK)
QK.shape

(4, 4)

In [ ]:
V = np.dot(X, Wv)

In [ ]:
V.shape

(4, 12)

In [ ]:
QKV = np.dot(scaled_QK, V)

In [ ]:
QKV.shape

(4, 12)

## Create function for self attention

In [ ]:
def scaled_self_attention(query, key, value):
  key_dim = key.shape[1]
  QK = np.dot(query,key.T)
  #/np.sqrt(key_dim)
  print("---")
  print(QK.shape)
  #sf = nn.Softmax( dim=1)
  scaled_QK = softmax(QK)
  print(scaled_QK.shape)
  QKV = np.dot(scaled_QK, value)
  print(QKV.shape)
  return QKV, scaled_QK

In [ ]:
scaled_self_attention(Q, K, V)

(array([[ 6.59297357e-47,  6.11623018e-47,  2.09227010e-46,
          1.90797248e-46, -1.28153513e-47, -1.09696246e-46,
          2.74316935e-47, -6.58638251e-47, -1.39020227e-46,
          2.01060110e-46,  7.13266126e-47, -1.89522458e-46],
        [ 5.41346164e-40,  4.36153826e-40,  1.57390668e-39,
          1.45347501e-39, -7.28558597e-41, -8.25978126e-40,
          1.33804646e-40, -5.33975408e-40, -1.09072760e-39,
          1.56123496e-39,  5.51334414e-40, -1.46958532e-39],
        [-8.43764302e+00,  8.77144346e+00, -9.46910444e-01,
          2.97250628e+00,  2.36695398e+00, -3.98113213e+00,
         -2.28811882e+00,  4.45762186e+00,  4.50286565e+00,
          1.52476604e+00,  2.72580162e+00, -3.35865925e-01],
        [ 7.66125828e-32, -3.30838028e-32,  8.32463766e-32,
          1.97255430e-32, -6.90215186e-32, -3.29037147e-31,
         -6.06296034e-32,  1.18175743e-31,  1.12543985e-31,
          4.17384358e-32,  1.40384174e-31, -3.48219463e-32]]),
 array([[9.02178750e-65, 3.9612105

## Multi head attention

In [ ]:
seq_len = 3
embed_dim = 4

queries = np.random.rand(seq_len, embed_dim)
keys = np.random.rand(seq_len, embed_dim)
values = np.random.rand(seq_len, embed_dim)

print("Queries:\n", queries)

Queries:
 [[0.28484049 0.03688695 0.60956433 0.50267902]
 [0.05147875 0.27864646 0.90826589 0.23956189]
 [0.14489487 0.48945276 0.98565045 0.24205527]]


In [ ]:
output, attn_weights = scaled_self_attention(queries, keys, values)

print("Output\n", output, "\n")
print("Weights\n", attn_weights)

(3, 3)
(3, 3)
Output
 [[0.34046052 0.3583313  0.65012393 0.09111357]
 [0.40349096 0.37504672 0.71582375 0.1059299 ]
 [0.49985446 0.47074605 0.89351946 0.13143174]] 

Weights
 [[0.3254204  0.28426828 0.26285964]
 [0.29641855 0.31901007 0.33004653]
 [0.37816105 0.39672165 0.40709382]]


In [28]:
batch_size = 1
seq_len = 3
embed_dim = 12
num_heads = 3
head_dim = embed_dim // num_heads

In [29]:
x = np.random.rand(batch_size, seq_len, embed_dim).round(1)
print("Input shape: ", x.shape, "\n")
print("Input:\n", x)

Input shape:  (1, 3, 12) 

Input:
 [[[0.4 1.  0.7 0.6 0.2 0.2 0.1 0.9 0.6 0.7 0.  1. ]
  [0.8 0.2 0.2 0.2 0.3 0.5 0.4 0.3 0.6 0.1 0.3 0.4]
  [0.5 0.8 0.2 0.5 0.6 0.  0.6 0.2 0.1 0.9 1.  0.8]]]


In [ ]:
# The query weights for each head.
wq0 = np.random.rand(embed_dim, head_dim).round(1)
wq1 = np.random.rand(embed_dim, head_dim).round(1)
wq2 = np.random.rand(embed_dim, head_dim).round(1)

# The key weights for each head. 
wk0 = np.random.rand(embed_dim, head_dim).round(1)
wk1 = np.random.rand(embed_dim, head_dim).round(1)
wk2 = np.random.rand(embed_dim, head_dim).round(1)

# The value weights for each head.
wv0 = np.random.rand(embed_dim, head_dim).round(1)
wv1 = np.random.rand(embed_dim, head_dim).round(1)
wv2 = np.random.rand(embed_dim, head_dim).round(1)

In [ ]:
print("The three sets of query weights (one for each head):")
print("wq0:\n", wq0)
print("wq1:\n", wq1)
print("wq2:\n", wq1)

The three sets of query weights (one for each head):
wq0:
 [[0.9 0.6 0.3 0.3]
 [0.7 0.9 0.9 0.8]
 [0.6 0.1 0.2 0.9]
 [0.6 0.  0.1 0.7]]
wq1:
 [[0.  0.2 0.5 0.7]
 [0.7 0.2 0.7 0.2]
 [0.3 0.7 0.6 0.8]
 [0.7 0.6 0.1 0.4]]
wq2:
 [[0.  0.2 0.5 0.7]
 [0.7 0.2 0.7 0.2]
 [0.3 0.7 0.6 0.8]
 [0.7 0.6 0.1 0.4]]


In [ ]:
# Geneated queries, keys, and values for the first head.
q0 = np.dot(x, wq0)
k0 = np.dot(x, wk0)
v0 = np.dot(x, wv0)

# Geneated queries, keys, and values for the second head.
q1 = np.dot(x, wq1)
k1 = np.dot(x, wk1)
v1 = np.dot(x, wv1)

# Geneated queries, keys, and values for the third head.
q2 = np.dot(x, wq2)
k2 = np.dot(x, wk2)
v2 = np.dot(x, wv2)

In [ ]:
print("Q, K, and V for first head:\n")

print(f"q0 {q0.shape}:\n", q0, "\n")
print(f"k0 {k0.shape}:\n", k0, "\n")
print(f"v0 {v0.shape}:\n", v0)

Q, K, and V for first head:

q0 (1, 3, 4):
 [[[1.42 0.36 0.45 1.61]
  [1.6  0.89 0.94 1.79]
  [1.19 0.49 0.44 1.03]]] 

k0 (1, 3, 4):
 [[[1.98 1.47 0.76 1.12]
  [1.61 1.83 0.91 1.5 ]
  [1.36 1.04 0.74 0.98]]] 

v0 (1, 3, 4):
 [[[0.98 0.85 1.   0.68]
  [1.35 0.92 0.85 0.79]
  [0.48 0.85 0.53 0.65]]]


In [ ]:
import tensorflow as tf
def scaled_dot_product_attention(query, key, value, mask=None):
  key_dim = tf.cast(tf.shape(key)[-1], tf.float32)
  scaled_scores = tf.matmul(query, key, transpose_b=True) / np.sqrt(key_dim)

  if mask is not None:
    scaled_scores = tf.where(mask==0, -np.inf, scaled_scores)

  softmax = tf.keras.layers.Softmax()
  weights = softmax(scaled_scores) 
  return tf.matmul(weights, value), weights

In [ ]:
out0, attn_weights0 = scaled_self_attention(q0, k0, v0)

print("Output from first attention head: ", out0, "\n")
print("Attention weights from first head: ", attn_weights0)

ValueError: ignored

In [30]:
batch_size = 1
seq_len = 3
embed_dim = 12
num_heads = 3
head_dim = embed_dim // num_heads

In [31]:
## to overcome problems with numpy dot product for batch
## create torch array

x = torch.randn(batch_size, seq_len, embed_dim)

print("Input shape: ", x.shape, "\n")
print("Input:\n", x)

Input shape:  torch.Size([1, 3, 12]) 

Input:
 tensor([[[ 0.2619, -1.5973,  0.2629,  0.0645,  0.2112, -0.4840,  0.4545,
           0.2482,  1.9125, -0.5893,  0.7240,  1.7931],
         [ 1.5193,  0.6065, -1.8665,  1.1290, -1.0805,  0.1319,  1.2407,
          -0.2018, -0.3274, -1.0611,  0.3008, -0.0039],
         [ 0.3538,  0.7198, -0.4635,  1.8290,  0.4108, -0.5122,  0.1376,
          -1.3006,  0.0455,  0.6456, -1.1356,  1.3295]]])


In [32]:
wq0 = torch.rand(embed_dim, head_dim)
wq1 = torch.rand(embed_dim, head_dim)
wq2 = torch.rand(embed_dim, head_dim)

# The key weights for each head. 
wk0 = torch.rand(embed_dim, head_dim)
wk1 = torch.rand(embed_dim, head_dim)
wk2 = torch.rand(embed_dim, head_dim)

# The value weights for each head.
wv0 = torch.rand(embed_dim, head_dim)
wv1 = torch.rand(embed_dim, head_dim)
wv2 = torch.rand(embed_dim, head_dim)

In [33]:
wq0.shape

torch.Size([12, 4])

In [34]:
torch.matmul(x,wq0)

tensor([[[ 0.6788,  1.7449, -0.4234,  0.7830],
         [-0.5399,  0.5887, -0.0268, -1.2599],
         [ 2.4524,  2.3112,  1.5315,  0.1854]]])

In [35]:
torch.einsum('bij,jk->bik', x, wq0)

tensor([[[ 0.6788,  1.7449, -0.4234,  0.7830],
         [-0.5399,  0.5887, -0.0268, -1.2599],
         [ 2.4524,  2.3112,  1.5315,  0.1854]]])

In [36]:
softmax_function = nn.Softmax(dim=1)
input = torch.randn(2, 3)
print(input)
output = softmax_function(input)
output

tensor([[-0.1177,  1.2033,  0.1428],
        [ 1.5842, -2.2718, -0.4053]])


tensor([[0.1654, 0.6199, 0.2147],
        [0.8636, 0.0183, 0.1181]])

In [37]:
def scaled_self_attention_torch(query, key, value):
  key_dim = key.shape[1]
  QK = torch.div(torch.matmul(query,key.T),np.sqrt(key_dim))
  print("---")
  print(QK.shape)
  #sf = nn.Softmax( dim=1)
  scaled_QK = softmax_function(QK)
  print(scaled_QK.shape)
  QKV = torch.matmul(scaled_QK, value)
  print(QKV.shape)
  return QKV, scaled_QK

In [38]:
# Geneated queries, keys, and values for the first head.
q0 = torch.matmul(x, wq0)
k0 = torch.matmul(x, wk0)
v0 = torch.matmul(x, wv0)

# Geneated queries, keys, and values for the second head.
q1 = torch.matmul(x, wq1)
k1 = torch.matmul(x, wk1)
v1 = torch.matmul(x, wv1)

# Geneated queries, keys, and values for the third head.
q2 = torch.matmul(x, wq2)
k2 = torch.matmul(x, wk2)
v2 = torch.matmul(x, wv2)

In [39]:
print("Q, K, and V for first head:\n")

print(f"q0 {q0.shape}:\n", q0, "\n")
print(f"k0 {k0.shape}:\n", k0, "\n")
print(f"v0 {v0.shape}:\n", v0)

Q, K, and V for first head:

q0 torch.Size([1, 3, 4]):
 tensor([[[ 0.6788,  1.7449, -0.4234,  0.7830],
         [-0.5399,  0.5887, -0.0268, -1.2599],
         [ 2.4524,  2.3112,  1.5315,  0.1854]]]) 

k0 torch.Size([1, 3, 4]):
 tensor([[[ 1.4471,  0.4132,  1.3002,  1.5290],
         [-0.7078,  1.5979, -1.0892, -0.1337],
         [-1.7239,  0.2325,  0.2377,  0.6269]]]) 

v0 torch.Size([1, 3, 4]):
 tensor([[[ 1.3706,  1.3796,  1.2966,  1.5465],
         [-0.9009,  0.9481,  0.7197,  1.5377],
         [ 0.1803,  1.6086,  0.4795,  1.4874]]])


In [40]:
out0, attn_weights0 = scaled_self_attention_torch(q0, k0, v0)

print("Output from first attention head: ", out0, "\n")
print("Attention weights from first head: ", attn_weights0)

<ipython-input-37-331783bca393>:3: UserWarning: The use of `x.T` on tensors of dimension other than 2 to reverse their shape is deprecated and it will throw an error in a future release. Consider `x.mT` to transpose batches of matrices or `x.permute(*torch.arange(x.ndim - 1, -1, -1))` to reverse the dimensions of a tensor. (Triggered internally at ../aten/src/ATen/native/TensorShape.cpp:3277.)
  QK = torch.div(torch.matmul(query,key.T),np.sqrt(key_dim))


RuntimeError: ignored

In [42]:
q0

tensor([[[ 0.6788,  1.7449, -0.4234,  0.7830],
         [-0.5399,  0.5887, -0.0268, -1.2599],
         [ 2.4524,  2.3112,  1.5315,  0.1854]]])

In [43]:
k0

tensor([[[ 1.4471,  0.4132,  1.3002,  1.5290],
         [-0.7078,  1.5979, -1.0892, -0.1337],
         [-1.7239,  0.2325,  0.2377,  0.6269]]])

In [44]:
k0.T

tensor([[[ 1.4471],
         [-0.7078],
         [-1.7239]],

        [[ 0.4132],
         [ 1.5979],
         [ 0.2325]],

        [[ 1.3002],
         [-1.0892],
         [ 0.2377]],

        [[ 1.5290],
         [-0.1337],
         [ 0.6269]]])

In [41]:
torch.einsum('bij,bkj->bik', q0, k0)

tensor([[[ 2.3498,  2.6644, -0.3742],
         [-2.4992,  1.5205,  0.2715],
         [ 6.7784,  0.2647, -3.2098]]])

In [45]:
## Changing our self attention function

def scaled_self_attention_torch(query, key, value):
  key_dim = key.shape[1]
  QK = torch.div(torch.einsum('bij,bkj->bik',query,key),np.sqrt(key_dim))
  print("---")
  print(QK.shape)
  #sf = nn.Softmax( dim=1)
  scaled_QK = softmax_function(QK)
  print(scaled_QK.shape)
  QKV = torch.matmul(scaled_QK, value)
  print(QKV.shape)
  return QKV, scaled_QK

In [47]:
out0, attn_weights0 = scaled_self_attention_torch(q0, k0, v0)

print("Output from first attention head: \n", out0, "\n")
print("Attention weights from first head: \n", attn_weights0)

---
torch.Size([1, 3, 3])
torch.Size([1, 3, 3])
torch.Size([1, 3, 4])
Output from first attention head: 
 tensor([[[-0.3435,  1.2433,  0.6814,  1.5432],
         [-0.1585,  1.1657,  0.4791,  1.2723],
         [ 1.1521,  1.5272,  1.3352,  1.7561]]]) 

Attention weights from first head: 
 tensor([[[0.0717, 0.5660, 0.3779],
         [0.0044, 0.2924, 0.5486],
         [0.9240, 0.1416, 0.0735]]])
