<a href="https://colab.research.google.com/github/panditamey1/NLP_transformers/blob/main/transformers_pytorch_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Self attention


Key, Query, Value 
- Create matrices for KQV
 

In [41]:
import numpy as np
np.random.seed(42)
from torch import nn


In [ ]:
t = 4
d = 12 # model dimensions

Wk = np.random.randn(d,d)
Wq = np.random.randn(d,d)
Wv = np.random.randn(d,d)

Wk.shape

(12, 12)

In [ ]:
X = np.random.randn(t,d)  # t = token size

In [ ]:
X.shape


(4, 12)

- take dot product of (Q*K.T/np.sqrt(d) )* V

In [ ]:
Q = np.dot(X, Wq)
K = np.dot(X, Wk)

K.shape

(4, 12)

In [ ]:
## dot product of q and k

QK = np.dot(Q,K.T)


In [ ]:
QK = QK / np.sqrt(d)

In [55]:
## Softmax
def softmax(x):
    e_x = np.exp(x - np.max(x))
    print(e_x.shape)
    res =  e_x / e_x.sum(axis=0) # only difference
    print(res.shape)
    return res
    

In [ ]:
scaled_QK = softmax(QK)
QK.shape

(4, 4)

In [ ]:
V = np.dot(X, Wv)

In [ ]:
V.shape

(4, 12)

In [ ]:
QKV = np.dot(scaled_QK, V)

In [ ]:
QKV.shape

(4, 12)

## Create function for self attention

In [72]:
def scaled_self_attention(query, key, value):
  key_dim = key.shape[1]
  QK = np.dot(query,key.T)
  #/np.sqrt(key_dim)
  print("---")
  print(QK.shape)
  #sf = nn.Softmax( dim=1)
  scaled_QK = softmax(QK)
  print(scaled_QK.shape)
  QKV = np.dot(scaled_QK, value)
  print(QKV.shape)
  return QKV, scaled_QK

In [ ]:
scaled_self_attention(Q, K, V)

(array([[ 6.59297357e-47,  6.11623018e-47,  2.09227010e-46,
          1.90797248e-46, -1.28153513e-47, -1.09696246e-46,
          2.74316935e-47, -6.58638251e-47, -1.39020227e-46,
          2.01060110e-46,  7.13266126e-47, -1.89522458e-46],
        [ 5.41346164e-40,  4.36153826e-40,  1.57390668e-39,
          1.45347501e-39, -7.28558597e-41, -8.25978126e-40,
          1.33804646e-40, -5.33975408e-40, -1.09072760e-39,
          1.56123496e-39,  5.51334414e-40, -1.46958532e-39],
        [-8.43764302e+00,  8.77144346e+00, -9.46910444e-01,
          2.97250628e+00,  2.36695398e+00, -3.98113213e+00,
         -2.28811882e+00,  4.45762186e+00,  4.50286565e+00,
          1.52476604e+00,  2.72580162e+00, -3.35865925e-01],
        [ 7.66125828e-32, -3.30838028e-32,  8.32463766e-32,
          1.97255430e-32, -6.90215186e-32, -3.29037147e-31,
         -6.06296034e-32,  1.18175743e-31,  1.12543985e-31,
          4.17384358e-32,  1.40384174e-31, -3.48219463e-32]]),
 array([[9.02178750e-65, 3.9612105

## Multi head attention

In [57]:
seq_len = 3
embed_dim = 4

queries = np.random.rand(seq_len, embed_dim)
keys = np.random.rand(seq_len, embed_dim)
values = np.random.rand(seq_len, embed_dim)

print("Queries:\n", queries)

Queries:
 [[0.28484049 0.03688695 0.60956433 0.50267902]
 [0.05147875 0.27864646 0.90826589 0.23956189]
 [0.14489487 0.48945276 0.98565045 0.24205527]]


In [58]:
output, attn_weights = scaled_self_attention(queries, keys, values)

print("Output\n", output, "\n")
print("Weights\n", attn_weights)

(3, 3)
(3, 3)
Output
 [[0.34046052 0.3583313  0.65012393 0.09111357]
 [0.40349096 0.37504672 0.71582375 0.1059299 ]
 [0.49985446 0.47074605 0.89351946 0.13143174]] 

Weights
 [[0.3254204  0.28426828 0.26285964]
 [0.29641855 0.31901007 0.33004653]
 [0.37816105 0.39672165 0.40709382]]


In [29]:
batch_size = 1
seq_len = 4
embed_dim = 12
num_heads = 3
head_dim = embed_dim // num_heads

In [59]:
x = np.random.rand(batch_size, seq_len, embed_dim).round(1)
print("Input shape: ", x.shape, "\n")
print("Input:\n", x)

Input shape:  (1, 3, 4) 

Input:
 [[[0.3 0.1 0.9 0.9]
  [0.3 0.7 0.8 0.6]
  [0.5 0.2 0.1 0.9]]]


In [60]:
# The query weights for each head.
wq0 = np.random.rand(embed_dim, head_dim).round(1)
wq1 = np.random.rand(embed_dim, head_dim).round(1)
wq2 = np.random.rand(embed_dim, head_dim).round(1)

# The key weights for each head. 
wk0 = np.random.rand(embed_dim, head_dim).round(1)
wk1 = np.random.rand(embed_dim, head_dim).round(1)
wk2 = np.random.rand(embed_dim, head_dim).round(1)

# The value weights for each head.
wv0 = np.random.rand(embed_dim, head_dim).round(1)
wv1 = np.random.rand(embed_dim, head_dim).round(1)
wv2 = np.random.rand(embed_dim, head_dim).round(1)

In [61]:
print("The three sets of query weights (one for each head):")
print("wq0:\n", wq0)
print("wq1:\n", wq1)
print("wq2:\n", wq1)

The three sets of query weights (one for each head):
wq0:
 [[0.9 0.6 0.3 0.3]
 [0.7 0.9 0.9 0.8]
 [0.6 0.1 0.2 0.9]
 [0.6 0.  0.1 0.7]]
wq1:
 [[0.  0.2 0.5 0.7]
 [0.7 0.2 0.7 0.2]
 [0.3 0.7 0.6 0.8]
 [0.7 0.6 0.1 0.4]]
wq2:
 [[0.  0.2 0.5 0.7]
 [0.7 0.2 0.7 0.2]
 [0.3 0.7 0.6 0.8]
 [0.7 0.6 0.1 0.4]]


In [62]:
# Geneated queries, keys, and values for the first head.
q0 = np.dot(x, wq0)
k0 = np.dot(x, wk0)
v0 = np.dot(x, wv0)

# Geneated queries, keys, and values for the second head.
q1 = np.dot(x, wq1)
k1 = np.dot(x, wk1)
v1 = np.dot(x, wv1)

# Geneated queries, keys, and values for the third head.
q2 = np.dot(x, wq2)
k2 = np.dot(x, wk2)
v2 = np.dot(x, wv2)

In [63]:
print("Q, K, and V for first head:\n")

print(f"q0 {q0.shape}:\n", q0, "\n")
print(f"k0 {k0.shape}:\n", k0, "\n")
print(f"v0 {v0.shape}:\n", v0)

Q, K, and V for first head:

q0 (1, 3, 4):
 [[[1.42 0.36 0.45 1.61]
  [1.6  0.89 0.94 1.79]
  [1.19 0.49 0.44 1.03]]] 

k0 (1, 3, 4):
 [[[1.98 1.47 0.76 1.12]
  [1.61 1.83 0.91 1.5 ]
  [1.36 1.04 0.74 0.98]]] 

v0 (1, 3, 4):
 [[[0.98 0.85 1.   0.68]
  [1.35 0.92 0.85 0.79]
  [0.48 0.85 0.53 0.65]]]


In [69]:
import tensorflow as tf
def scaled_dot_product_attention(query, key, value, mask=None):
  key_dim = tf.cast(tf.shape(key)[-1], tf.float32)
  scaled_scores = tf.matmul(query, key, transpose_b=True) / np.sqrt(key_dim)

  if mask is not None:
    scaled_scores = tf.where(mask==0, -np.inf, scaled_scores)

  softmax = tf.keras.layers.Softmax()
  weights = softmax(scaled_scores) 
  return tf.matmul(weights, value), weights

In [73]:
out0, attn_weights0 = scaled_self_attention(q0, k0, v0)

print("Output from first attention head: ", out0, "\n")
print("Attention weights from first head: ", attn_weights0)

ValueError: ignored